name: wellio-fit
services:
  app:
    container_name: wellio-fit
    build:
      context: .
      args:
        BUNDLE_WITHOUT: ""
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      -  .:/var/www/wellio-fit/current
  db:
    container_name: wellio-fit-database
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust