name: wellio-fit
services:
  app:
    container_name: wellio-fit-api
    build:
      context: . # use the current directory as the build context
      args:
        BUNDLE_WITHOUT: ""
    env_file:
      - .env
    ports:
      - "3000:3000" # map the container port to the host port
    volumes:
      -  .:/var/www/wellio-fit/current
  db:
    container_name: wellio-fit-database
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wellio-fit-development
    volumes:
      - db_data:/var/lib/postgresql/data # persist data even if container shuts down

volumes:
  db_data:
    driver: local # default