name: quequeo
services:
  app:
    container_name: api-quequeo
    build:
      context: . # use the current directory as the build context
      args:
        BUNDLE_WITHOUT: ""
    env_file:
      - .env
    ports:
      - "3000:3000" # map the container port to the host port
    volumes:
      -  .:/var/www/api-quequeo/current
    command: sh -c "RAILS_ENV=production bundle exec rails server -b '0.0.0.0'"
  db:
    container_name: api-quequeo-database
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api-quequeo-production
    volumes:
      - db_data:/var/lib/postgresql/data # persist data even if container shuts down

volumes:
  db_data:
    driver: local # default