name: quequeo
services:
  app:
    container_name: api-quequeo
    build:
      context: .
      args:
        BUNDLE_WITHOUT: ""
    env_file:
      - .env
    environment:
      - RAILS_ENV=production
    ports:
      - "3000:3000"
    volumes:
      -  .:/var/www/api-quequeo/current
    stdin_open: true
    tty: true
    command: sh -c "bundle exec rails server -b '0.0.0.0'"
  db:
    container_name: api-quequeo-database
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api-quequeo-production
      - POSTGRES_HOST=db
    volumes:
      - db_data:/var/lib/postgresql/data # persist data even if container shuts down

volumes:
  db_data:
    driver: local