default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
  database: <%= ENV.fetch("POSTGRES_DEV_DB", "db") %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_TEST_DB', 'wellio_test') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '123456') %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_PROD_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>