default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: postgres
  port: 5432

development:
  <<: *default
  database: api-quequeo-development

test:
  <<: *default
  database: api-quequeo-test

production:
  <<: *default
  database: api-quequeo-production