common: &defaults
  key: ENV['SCOUT_APM_KEY']
  log_level: debug
  name: Quequeo API
  monitor: true

production:
  <<: *defaults

development:
  <<: *defaults
  monitor: false

test:
  <<: *defaults
  monitor: false

staging:
  <<: *defaults