name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [ main ]
    types:
      - completed

jobs:
  build:

    runs-on: self-hosted

    # Dockerhub pull + delete + run
    # steps:
    #   - name: Pull the Docker image
    #     run: sudo docker pull monitoapps/api-wellio-fit:latest
    #   - name: Delete the old docker container
    #     run: sudo docker rm -f api-wellio-fit-container || true
    #   - name: Run the Docker container
    #     run: sudo docker run -d -p 3000:3000 --name api-wellio-fit-container monitoapps/api-wellio-fit:latest

    # Github Container Registry pull + delete + run
    # steps:
    #   - name: Login to GitHub Container Registry
    #     run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "quequeo" --password-stdin

    #   - name: Pull the Docker image
    #     run: sudo docker pull ghcr.io/quequeo/api-wellio-fit:latest

    #   - name: Delete the old Docker container
    #     run: sudo docker rm -f api-wellio-fit-container || true

    #   - name: Run the Docker container
    #     run: sudo docker run -d -p 3000:3000 --name api-wellio-fit-container ghcr.io/quequeo/api-wellio-fit:latest

    # AWS ECR pull + delete + run
    steps:
      - name: Set up AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Login to ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 663622660063.dkr.ecr.us-east-1.amazonaws.com

      - name: Install jq
        run: sudo apt-get install jq
      
      - name: Delete old Docker images from ECR
        run: |
          aws ecr list-images --repository-name monitoapps/api-wellio-fit --query 'imageIds[?imageTag!=`latest`]' --output json | \
          jq -r '.[] | {imageDigest: .imageDigest}' | \
          aws ecr batch-delete-image --repository-name monitoapps/api-wellio-fit --image-ids file://<(cat)

      - name: Pull the Docker image
        run: sudo docker pull 663622660063.dkr.ecr.us-east-1.amazonaws.com/monitoapps/api-wellio-fit:latest

      - name: Delete the old Docker container
        run: sudo docker rm -f api-wellio-fit-container || true

      - name: Run the Docker container
        run: sudo docker run -d -p 3000:3000 --name api-wellio-fit-container 663622660063.dkr.ecr.us-east-1.amazonaws.com/monitoapps/api-wellio-fit:latest


        


