name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [ main ]
    types:
      - completed

jobs:
  build:

    runs-on: self-hosted
    steps:
      - name: Pull the Docker image
        run: sudo docker pull monitoapps/api-wellio-fit:latest
      - name: Delete the old docker container
        run: sudo docker rm -f api-wellio-fit-container || true
      - name: Run the Docker container
        run: sudo docker run -d -p 3000:3000 --name api-wellio-fit-container monitoapps/api-wellio-fit:latest



        


