name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [ main ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key for EC2
        # EC2_SSH_PRIVATE_KEY: content of .pem file (aws ec2 key pair)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to EC2 (Git pull)
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << EOF
          cd app/api-quequeo

          # Update code
          git reset --hard origin/main
          git pull origin main

          # Config environment variables
          export RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
          export RAILS_ENV=production
          export POSTGRES_HOST=db
          export POSTGRES_USER=postgres
          export POSTGRES_DB=api-quequeo-production
          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}

          # Reset container
          docker-compose stop app
          docker-compose rm -f app
          docker-compose build app
          docker-compose up -d --remove-orphans app
          EOF
    

